### PR TITLE
fix: new Home channels, reorder and add channels to Discover

### PR DESCRIPTION
**Pull request by nlewis84**
This should not go live until @conrad-vanl gives us the go ahead.

https://user-images.githubusercontent.com/72768221/132742765-61e6f37d-1f91-4e0f-b028-474d6005134a.mp4

https://user-images.githubusercontent.com/72768221/132742777-4e156823-0aeb-4c67-89e6-2ceccf3f9593.mp4

### CODE REVIEW

**Review by redreceipt — APPROVED** [review]

**Comment by nlewis84** [comment]
@conrad-vanl @redreceipt Can I merge this? I don't know what the protocol is for Grace since it is live. Working on another PR to add priority to these new channels.

**Comment by nlewis84** [comment]
I take it back on adding priority. v1 has a much different setup than I expected.

**Comment by conrad-vanl** [comment]
Merged at request of client. @nlewis84 yeah and I think Grace's priority order moves in the opposite direction - we have an example of it here https://github.com/Differential/grace-apollos-app/blob/10a0b8e4e26d8f685ea413caeca93e94c58e7c6d/apollos-api/src/data/Feature.js#L208

So that means that these new sections don't use priority order right now, correct?

**Comment by nlewis84** [comment]
I believe that is correct. They do not use priority. We should set the algorithm for channelIds 22 and 23 to be FEATURED_CAMPAIGN. In v2 apps, that would be done in the config.yml. I'm not sure where that would be in this app.
Screen Shot 2021-09-24 at 9 23 50 AM

Maybe in here somewhere?
Screen Shot 2021-09-24 at 9 25 34 AM

**Comment by conrad-vanl** [comment]
Ah, I'm only referring to priority on the home tab. I think the discover tab is okay the way it is.

**Comment by nlewis84** [comment]
I was working off this email mostly. I think we are good with Home Tab the way it is in this PR and she was wanting priority on the Discover tab. At least, that's how I read it.

Screen Shot 2021-09-24 at 9 34 50 AM

**Comment by conrad-vanl** [comment]
Yeah, you're right. Ok. I can talk to her more about that. Thank you!

**Pull request merged**
