### PR TITLE
feat: Api 2.0

### PR DESCRIPTION
**Pull request by nlewis84**
This PR is an upgrade of their API to v2.

## Testing
Spin this PR up locally and QA the app in the simulator

### CODE REVIEW

**Comment by nlewis84** [comment]
@redreceipt Here's the API upgrade draft PR.

**Comment by nlewis84** [comment]
Something that I'm noticing now here on GH is that the GH Actions are not up to date (they don't look like all the other newer apps)

**Comment by redreceipt** [comment]
API doesn't start
Screen Shot 2021-11-22 at 10 41 04 AM

**Comment by nlewis84** [comment]
Strange. I just booted it up fine. Regardless, I must have been seeing some cached data on Friday. The Home tab is completely blank for me, so I don't think this is quite ready for review yet. The other tabs are working fine though!

https://user-images.githubusercontent.com/72768221/142893714-feb9b5e0-f2ec-4e93-939a-488c791706c5.mp4

**Pull request merged**
