### PR TITLE
feat: App 2.0

### PR DESCRIPTION
**Pull request by nlewis84**
This PR is an upgrade to version 2 of the app.

### CODE REVIEW

**Comment by nlewis84** [comment]
@redreceipt API upgrade is working. APP upgrade is not yet. I would appreciate your eyes and comments on the work so far.

**Comment by nlewis84** [comment]
I have taken care of all the merge conflicts.

**Comment by redreceipt** [comment]
@nlewis84 have you tried just upgrading the API first with a v1 app? that would be less risky and easier to QA.

**Comment by nlewis84** [comment]
I did the API upgrade first and everything seemed to be working in the app.

**Comment by redreceipt** [comment]
Can we split that out into a separate PR and do a two part release and QA?

**Comment by redreceipt** [comment]
We just had lots of problems with the LCBC upgrade and learned our lesson.

**Comment by nlewis84** [comment]
I'll leave this PR to be the APP branch. 

Here is the API branch. https://github.com/Differential/grace-apollos-app/pull/34

**Pull request merged**
