### PR TITLE
chore: update secrets to grab new Rock Token

### PR DESCRIPTION
**Pull request by nlewis84**
I was 'iffy' on if I did this correctly, since this is an older app. I pulled down the latest changes, ran `apollos secrets -d <theSecret>`, changed the Rock Token to the new one, ran `apollos secrets -e <theSecret>`.

Anything I missed @redreceipt?

### CODE REVIEW

**Comment by redreceipt** [comment]
the rock token isn't in the app secrets? confused on what this PR is doing

**Comment by nlewis84** [comment]
The Rock token that was updated this morning was not the same one that was in the `.env.shared` file. This updates the ROCK_TOKEN to match the one in Heroku.

**Comment by redreceipt** [comment]
that file is irrelevant and should probably just be deleted. and this PR shows changing app folder secrets too

**Comment by nlewis84** [comment]
Okay, well if that file is irrelevant, so is this PR.

**Pull request closed without merging**
